name: .NET CI/CD

on:
  push:
    branches: [ main, refactor/*, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        working-directory: src/WarehouseApp
        run: dotnet restore

      - name: Build solution
        working-directory: .
        run: dotnet build warehouse-app.sln --no-restore --configuration Release

      - name: Run code analysis
        working-directory: src/WarehouseApp
        run: dotnet build --no-restore --configuration Release /p:EnableNETAnalyzers=true

      - name: Run EF migrations script (dry-run)
        working-directory: src/WarehouseApp
        run: |
          dotnet tool install --global dotnet-ef
          export PATH="$HOME/.dotnet/tools:$PATH"
          dotnet ef migrations script --idempotent

      - name: Run unit tests
        working-directory: WarehouseApp.Tests
        run: dotnet test --no-build --verbosity normal
