name: .NET CI/CD

on:
  push:
    branches: [ main, refactor/*, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore all projects
        run: dotnet restore "warehouse-app.sln"

      - name: Build solution
        run: dotnet build "warehouse-app.sln" --no-restore --configuration Release

      - name: Run code analysis
        run: dotnet build "src/WarehouseApp/WarehouseApp.csproj" --no-restore --configuration Release /p:EnableNETAnalyzers=true

      - name: Run unit tests
        run: dotnet test "warehouse-app.sln" --no-build --verbosity normal
