name: .NET CI/CD

on:
  push:
    branches: [ main, refactor/*, feature/* ]
  pull_request:
    branches: [ main ]

jobs:
  build-test-analyze:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore all projects
        run: dotnet restore "warehouse-app.sln"

      - name: Build solution
        run: dotnet build "warehouse-app.sln" --no-restore --configuration Release

      - name: Run code analysis
        run: dotnet build "src/WarehouseApp/WarehouseApp.csproj" --no-restore --configuration Release /p:EnableNETAnalyzers=true

      - name: Generate EF Core migrations script (dry-run)
        continue-on-error: true
        working-directory: src/WarehouseApp
        run: |
          dotnet tool install --global dotnet-ef
          export PATH="$HOME/.dotnet/tools:$PATH"
          dotnet ef migrations script --idempotent

      - name: Run unit tests
        working-directory: WarehouseApp.Tests
        run: dotnet vstest "./bin/Debug/net9.0/WarehouseApp.Tests.dll"
